#version 430

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (std430, binding = 0) buffer InputBuffer {
    vec3 data[];
};

void main() {
    vec3 total = vec3(0);
    for (int i = 0; i < data.length(); i++) {
        total.x += data[i].x;
        total.y += data[i].y;
        total.z += data[i].z;
    }
    if (total.x + total.y + total.z == 0) {
        data[0].x = 1;
    } else {
        data[0].x = 0;
    }
}
