#version 430

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (std430, binding = 0) buffer InputBuffer {
    int data[];
};

void main() {
    if (data[2] > 0 || (data[1] & 1) == 0) {
        data[0] = max(data[0]-data[2], 0);
        data[0] = max(data[0]-(data[1] & 1)*2, 0);
        data[0] = (data[0]+4-1)/4;
    } else {
        data[0] = (data[0]+4-1)/4;
    }
    data[1] = (data[1]+2-1)/2;
}
