#version 430

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (std430, binding = 0) buffer InputBuffer {
    uint data[];
};

void main() {
    uint hello[5] = {104, 101, 108, 108, 111};
    int hCount = 0;
    int j = 0;
    for (int i = 0; i < data.length(); i++) {
        if (data[i] == hello[j]) {
            j++;
        }
        if (j > 4) {
            data[0] = 1;
            return;
        }
    }
    data[0] = 0;
}
