#version 430

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (std430, binding = 0) buffer InputBuffer {
    uint data[];
};

void main() {
    vec3 checkStr = {72, 81, 57};
    for (int i = 0; i < data.length(); i++) {
        if (data[i] == checkStr.x || data[i] == checkStr.y || data[i] == checkStr.z) {
            data[0] = 1;
            return;
        }
    }
    data[0] = 0;
}
